<!-- <?php if ($block->getProducts()): ?>
    <div class="products-grid">
        <?php foreach ($block->getProducts() as $product): ?>
            <div class="product-item">
                <a href="<?php echo $product->getProductUrl(); ?>">
                    <img src="<?php echo $block->getProductImageUrl($product); ?>" alt="<?php echo $block->escapeHtml($product->getName()); ?>" />
                    <h2><?php echo $block->escapeHtml($product->getName()); ?></h2>
                    <span><?php echo $block->escapeHtml($product->getPrice()); ?></span>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <p>No products found ya Samir.</p>
<?php endif; ?> -->